version: '2.4'

services:
  traefik:
    image: library/traefik:1.7-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:80'
    command: |
      --docker
      --docker.domain=traefik
      --docker.watch
      --api
      --defaultentrypoints=http,https
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Host:trafik.localhost
    networks:
      - frontend
  nextjs:
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    networks:
      - frontend
    volumes:
      - .:/home/node/app
      - /home/node/node_modules
    labels:
      - traefik.port=3000
      - traefik.frontend.rule=Host:localhost
networks:
  frontend:
